INSERT INTO PERSON
(ID, NAME, LOCATION, BIRTH_DATE)
VALUES(381486, 'AMEY', 'JOHANNESBURG',sysdate());

INSERT INTO PERSON
(ID, NAME, LOCATION, BIRTH_DATE)
VALUES(381487, 'AMEY2', 'JOHANNESBURG',sysdate());

INSERT INTO PERSON
(ID, NAME, LOCATION, BIRTH_DATE)
VALUES(381488, 'AMEY3', 'JOHANNESBURG',sysdate());